version: '3.8'
services:
    react-container:
        container_name: react
        build:
            context: .
            dockerfile: react.dockerfile
        volumes:
            - ./ui:/app
            - /app/node_modules
        ports:
            - "3000:3000"
        environment:
            SERVICE_TAGE: ui

            
    php-apache-environment:
        container_name: php-apache
        restart: always
        build:
            context: ./back-end
            dockerfile: Dockerfile
        depends_on:
            - database
        volumes:
            - ./back-end:/var/www/html/
            - ./back-end/.htaccess:/var/www/html/.htaccess
            - /var/www/html/vendor
        ports:
            - "8000:80"
        environment:
            SERVICE_TAGE: app
    database:
        container_name: database
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password

        volumes:
            - ./back-end/database:/var/lib/mysql
        ports:
            - "3306"
    
    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     ports:
    #         - '8080:80'
    #     restart: always
    #     environment:
    #         PMA_HOST: db
    #         SERVICE_TAGE: phpmyadmin

    #     depends_on:
    #         - db
