# fly.toml app configuration file generated for back-end on 2023-10-09T00:48:28+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "back-end"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
